# Generated by Django 6.0.3 on 2026-06-17 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creneausemaine',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creneausemaine',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parametreentreprise',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parametreentreprise',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnel',
            name='departement',
            field=models.ForeignKey(blank=True, db_column='id_departement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.departement'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='porteentree',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='porteentree',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='creneausemaine',
            index=models.Index(fields=['jour_semaine'], name='creneaux_se_jour_se_39c5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='creneausemaine',
            index=models.Index(fields=['statut'], name='creneaux_se_statut_478fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='departement',
            index=models.Index(fields=['nom'], name='departement_nom_4ac3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='departement',
            index=models.Index(fields=['statut'], name='departement_statut_bcf937_idx'),
        ),
        migrations.AddIndex(
            model_name='parametreentreprise',
            index=models.Index(fields=['statut'], name='parametres__statut_2dedd8_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['nom'], name='personnel_nom_26dd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['prenom'], name='personnel_prenom_9d5b63_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['statut'], name='personnel_statut_1f770d_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['departement'], name='personnel_id_depa_3af8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='porteentree',
            index=models.Index(fields=['titre'], name='portes_entr_titre_93878c_idx'),
        ),
        migrations.AddIndex(
            model_name='porteentree',
            index=models.Index(fields=['statut'], name='portes_entr_statut_b54461_idx'),
        ),
    ]
