# Generated by Django 5.2.15 on 2026-07-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porteentree',
            name='titre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
