# Generated by Django 5.2.15 on 2026-07-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0003_alter_porteentree_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
