# Generated by Django 5.2.15 on 2026-07-22 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0004_alter_departement_nom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('libelle', models.CharField(help_text="Raison de l'exception (ex: 'Fête de l'Indépendance')", max_length=255)),
                ('est_chome', models.BooleanField(default=True, help_text='True = Férié chômé (pas de créneaux, 24h Hors-Normes). False = Férié travaillé (créneaux spécifiques définis dans ExceptionJourCreneau).')),
                ('statut', models.CharField(default='ACTIF', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'exceptions_jour',
                'db_table': 'exceptions_jour',
            },
        ),
        migrations.CreateModel(
            name='ExceptionJourCreneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('exception_jour', models.ForeignKey(db_column='id_exception_jour', on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='entreprise.exceptionjour')),
            ],
            options={
                'verbose_name_plural': 'exceptions_jour_creneaux',
                'db_table': 'exceptions_jour_creneaux',
            },
        ),
        migrations.AddIndex(
            model_name='exceptionjour',
            index=models.Index(fields=['date'], name='exceptions__date_441f24_idx'),
        ),
        migrations.AddIndex(
            model_name='exceptionjour',
            index=models.Index(fields=['statut'], name='exceptions__statut_2e5bd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='exceptionjour',
            constraint=models.UniqueConstraint(fields=('date',), name='uq_exception_jour_date'),
        ),
    ]
