# Generated by Django 5.2.15 on 2026-07-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0005_exceptionjour_exceptionjourcreneau_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceptionjourcreneau',
            name='exception_jour',
        ),
        migrations.DeleteModel(
            name='ExceptionJour',
        ),
        migrations.DeleteModel(
            name='ExceptionJourCreneau',
        ),
    ]
