# Generated by Django 5.2.15 on 2026-08-08 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0006_remove_exceptionjourcreneau_exception_jour_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('est_chome', models.BooleanField(default=False, help_text='Si coché, journée entièrement Hors-Normes (pas de créneaux)')),
                ('statut', models.CharField(default='ACTIF', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journée d'exception",
                'verbose_name_plural': "Journées d'exception",
                'db_table': 'exceptions_jour',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionJourCreneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('exception_jour', models.ForeignKey(db_column='id_exception_jour', on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='entreprise.exceptionjour')),
            ],
            options={
                'verbose_name': "Créneau d'exception",
                'verbose_name_plural': "Créneaux d'exception",
                'db_table': 'exceptions_jour_creneaux',
            },
        ),
    ]
