# Generated by Django 5.2.15 on 2026-08-10 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0007_add_exception_jour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='departement',
            field=models.ForeignKey(db_column='id_departement', default=1, on_delete=django.db.models.deletion.PROTECT, to='entreprise.departement'),
        ),
    ]
