# Generated by Django 6.0.6 on 2026-06-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LISTE_NOIRE', 'Liste noire'), ('INCIDENT', 'Incident'), ('OBJET_OUBLIE', 'Objet oublié')], max_length=20)),
                ('entite_id', models.PositiveIntegerField(db_column='id_entite')),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('lu_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'alerte',
                'verbose_name_plural': 'alertes',
                'db_table': 'alertes',
                'ordering': ['-created_at'],
            },
        ),
    ]
