# Generated by Django 6.0.3 on 2026-06-17 15:48

import core.compress_image
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree_max_minutes', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(default='ACTIF', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'types_visite',
            },
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('genre', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=50, null=True)),
                ('date_visite', models.DateTimeField(blank=True, null=True)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('date_depart_prevue', models.DateField(blank=True, null=True)),
                ('heure_depart_prevue', models.TimeField(blank=True, null=True)),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('numero_badge', models.CharField(blank=True, max_length=100, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('signature_entree', core.compress_image.CompressedImageField(blank=True, null=True, upload_to='signatures_entree/')),
                ('signature_sortie', core.compress_image.CompressedImageField(blank=True, null=True, upload_to='signatures_sortie/')),
                ('statut', models.CharField(default='EN_COURS', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(blank=True, db_column='id_employe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.personnel')),
                ('porte_entree', models.ForeignKey(db_column='id_porte_entree', on_delete=django.db.models.deletion.CASCADE, to='entreprise.porteentree')),
                ('type_visite', models.ForeignKey(db_column='id_type_visite', on_delete=django.db.models.deletion.CASCADE, to='visites.typevisite')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visites',
            },
        ),
        migrations.CreateModel(
            name='VisiteEnCours',
            fields=[
            ],
            options={
                'verbose_name': 'Visite en cours',
                'verbose_name_plural': 'Visites en cours',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('visites.visite',),
        ),
        migrations.CreateModel(
            name='VisiteExcedee',
            fields=[
            ],
            options={
                'verbose_name': 'Visite excédée',
                'verbose_name_plural': 'Visites excédées',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('visites.visite',),
        ),
        migrations.CreateModel(
            name='VisiteTerminee',
            fields=[
            ],
            options={
                'verbose_name': 'Visite terminée',
                'verbose_name_plural': 'Visites terminées',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('visites.visite',),
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=50, null=True)),
                ('date_naissance', models.CharField(blank=True, max_length=20, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=255, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('piece_identite', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_piece', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_nip', models.CharField(blank=True, max_length=100, null=True)),
                ('pays_delivrance', models.CharField(blank=True, max_length=100, null=True)),
                ('date_delivrance', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', core.compress_image.CompressedImageField(blank=True, null=True, upload_to='visiteurs/')),
                ('document_recto', core.compress_image.CompressedImageField(blank=True, null=True, upload_to='visiteurs/')),
                ('document_verso', core.compress_image.CompressedImageField(blank=True, null=True, upload_to='visiteurs/')),
                ('statut', models.CharField(default='ACTIF', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visiteurs',
            },
        ),
        migrations.AddField(
            model_name='visite',
            name='visiteur',
            field=models.ForeignKey(db_column='id_visiteur', on_delete=django.db.models.deletion.CASCADE, to='visites.visiteur'),
        ),
        migrations.AddIndex(
            model_name='typevisite',
            index=models.Index(fields=['nom'], name='types_visit_nom_21497d_idx'),
        ),
        migrations.AddIndex(
            model_name='typevisite',
            index=models.Index(fields=['statut'], name='types_visit_statut_f719cf_idx'),
        ),
        migrations.AddIndex(
            model_name='visiteur',
            index=models.Index(fields=['nom'], name='visiteurs_nom_f36ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='visiteur',
            index=models.Index(fields=['prenom'], name='visiteurs_prenom_ece8ea_idx'),
        ),
        migrations.AddIndex(
            model_name='visiteur',
            index=models.Index(fields=['statut'], name='visiteurs_statut_ea591c_idx'),
        ),
        migrations.AddIndex(
            model_name='visiteur',
            index=models.Index(fields=['nationalite'], name='visiteurs_nationa_880ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='visiteur',
            index=models.Index(fields=['numero_piece'], name='visiteurs_numero__d1f2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='visite',
            index=models.Index(fields=['statut'], name='visites_statut_8cdf5e_idx'),
        ),
        migrations.AddIndex(
            model_name='visite',
            index=models.Index(fields=['date_visite'], name='visites_date_vi_06889f_idx'),
        ),
        migrations.AddIndex(
            model_name='visite',
            index=models.Index(fields=['type_visite'], name='visites_id_type_2ea16e_idx'),
        ),
        migrations.AddIndex(
            model_name='visite',
            index=models.Index(fields=['visiteur'], name='visites_id_visi_e0dabd_idx'),
        ),
        migrations.AddIndex(
            model_name='visite',
            index=models.Index(fields=['porte_entree'], name='visites_id_port_e9ee6a_idx'),
        ),
        migrations.AddIndex(
            model_name='visite',
            index=models.Index(fields=['personnel'], name='visites_id_empl_e0cf9c_idx'),
        ),
    ]
