# Generated by Django 5.2.15 on 2026-06-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visite',
            options={'permissions': [('view_dashboard', 'Peut voir le tableau de bord et les statistiques')]},
        ),
    ]
