# Generated by Django 5.2.15 on 2026-06-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visites', '0002_add_view_dashboard_perm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visite',
            options={'permissions': [('view_stat_total_visits', 'Voir le total des visites'), ('view_stat_today_visits', 'Voir les visites du jour'), ('view_stat_en_cours', 'Voir les visites en cours'), ('view_stat_termine', 'Voir les visites terminées'), ('view_stat_excede', 'Voir les visites excédées'), ('view_stat_visiteurs', 'Voir le total des visiteurs'), ('view_stat_utilisateurs', 'Voir le total des utilisateurs'), ('view_stat_departements', 'Voir le total des départements'), ('view_stat_portes', "Voir le total des portes d'entrée"), ('view_stat_incidents', 'Voir le total des incidents'), ('view_stat_objets', 'Voir le total des objets oubliés'), ('view_stat_personnes_liste_noire', 'Voir les personnes en liste noire'), ('view_stat_detections_liste_noire', 'Voir les détections liste noire'), ('view_chart_departments', 'Voir le graphique par département'), ('view_chart_weekday', 'Voir le graphique par jour de la semaine'), ('view_chart_entry_points', "Voir le graphique par point d'entrée"), ('view_chart_incidents', 'Voir le flux des incidents'), ('view_chart_visit_types', 'Voir la répartition des types de visite')]},
        ),
    ]
