# Generated by Django 5.2.15 on 2026-07-07 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visites', '0004_add_termine_aujourdhui_perm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visiteur',
            index=models.Index(fields=['numero_nip'], name='visiteurs_numero__a94ca5_idx'),
        ),
    ]
