# Generated by Django 5.2.15 on 2026-07-07 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_initial'),
        ('visites', '0005_visiteur_visiteurs_numero__a94ca5_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visite',
            index=models.Index(fields=['statut', 'date_visite'], name='visites_statut_date_idx'),
        ),
        migrations.AddIndex(
            model_name='visiteur',
            index=models.Index(fields=['created_at'], name='visiteurs_created_6ff991_idx'),
        ),
    ]
