# Generated by Django 5.2.15 on 2026-07-22 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0005_exceptionjour_exceptionjourcreneau_and_more'),
        ('visites', '0006_visite_visites_statut_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='porte_entree',
            field=models.ForeignKey(blank=True, db_column='id_porte_entree', null=True, on_delete=django.db.models.deletion.CASCADE, to='entreprise.porteentree'),
        ),
    ]
