# Generated by Django 5.2.15 on 2026-07-22 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0005_exceptionjour_exceptionjourcreneau_and_more'),
        ('visites', '0007_make_porte_entree_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='departement',
            field=models.ForeignKey(blank=True, db_column='id_departement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.departement'),
        ),
    ]
