# Generated by Django 5.2.15 on 2026-07-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visites', '0008_add_departement_to_visite'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteur',
            name='flag_avertissement',
            field=models.BooleanField(default=False),
        ),
    ]
