# Generated by Django 5.2.15 on 2026-08-11 17:50

import core.compress_image
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visites', '0009_add_flag_avertissement_to_visiteur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentIdentite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_document', models.CharField(choices=[('CNI', 'CNI'), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de conduire'), ('CARTE_CONSULAIRE', 'Carte consulaire'), ('CARTE_SEJOUR', 'Carte de séjour'), ('CARTE_ETUDIANT', 'Carte étudiant'), ('AUTRE', 'Autre')], max_length=50)),
                ('numero_document', models.CharField(max_length=100)),
                ('pays_emetteur', models.CharField(blank=True, max_length=100, null=True)),
                ('date_delivrance', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('recto', core.compress_image.CompressedImageField(blank=True, null=True, upload_to='documents/')),
                ('verso', core.compress_image.CompressedImageField(blank=True, null=True, upload_to='documents/')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('PERDU', 'Perdu'), ('VOLE', 'Volé')], default='ACTIF', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visiteur', models.ForeignKey(db_column='id_visiteur', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='visites.visiteur')),
            ],
            options={
                'verbose_name': "Document d'identité",
                'verbose_name_plural': "Documents d'identité",
                'db_table': 'documents_identite',
                'indexes': [models.Index(fields=['numero_document'], name='documents_i_numero__283587_idx'), models.Index(fields=['type_document'], name='documents_i_type_do_864003_idx'), models.Index(fields=['visiteur'], name='documents_i_id_visi_95d7dd_idx'), models.Index(fields=['statut'], name='documents_i_statut_7d73bc_idx'), models.Index(fields=['date_expiration'], name='documents_i_date_ex_6a7f90_idx')],
                'constraints': [models.UniqueConstraint(fields=('type_document', 'numero_document'), name='uq_document_type_numero')],
            },
        ),
    ]
