# Generated by Django 5.2.15 on 2026-08-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visites', '0010_add_document_identite'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='numero_piece',
            field=models.CharField(blank=True, help_text='Numéro de document présenté lors de cette visite', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visite',
            name='piece_identite',
            field=models.CharField(blank=True, help_text='Type de document présenté lors de cette visite', max_length=50, null=True),
        ),
    ]
