# Generated by Django 6.0.3 on 2026-06-17 15:48

import core.compress_image
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('telephone_mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('photo_profil', core.compress_image.CompressedImageField(blank=True, null=True, upload_to='profils/')),
                ('statut', models.CharField(default='ACTIF', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('porte_entree', models.ForeignKey(blank=True, db_column='id_porte_entree', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.porteentree')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'db_table': 'utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(max_length=100)),
                ('entite', models.CharField(max_length=100)),
                ('entite_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, db_column='id_utilisateur', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'historiques_actions',
                'db_table': 'historiques_actions',
            },
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['statut'], name='utilisateur_statut_cab0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['porte_entree'], name='utilisateur_id_port_854441_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueaction',
            index=models.Index(fields=['utilisateur'], name='historiques_id_util_4602a2_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueaction',
            index=models.Index(fields=['action'], name='historiques_action_51ae41_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueaction',
            index=models.Index(fields=['entite'], name='historiques_entite_a9d2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueaction',
            index=models.Index(fields=['entite_id'], name='historiques_entite__dff823_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueaction',
            index=models.Index(fields=['created_at'], name='historiques_created_602e80_idx'),
        ),
    ]
