# Generated by Django 5.2.15 on 2026-07-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('entreprise', '0002_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['username'], name='utilisateur_usernam_cddbd8_idx'),
        ),
    ]
