# Generated by Django 6.0.3 on 2026-06-17 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionListeNoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_detection', models.DateTimeField(blank=True, null=True)),
                ('confiance', models.CharField(blank=True, default='MOYENNE', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(default='ACTIF', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'detections_liste_noire',
                'db_table': 'detections_liste_noire',
            },
        ),
        migrations.CreateModel(
            name='ListeNoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('motif', models.TextField(blank=True, null=True)),
                ('piece_identite', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_piece', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_nip', models.CharField(blank=True, max_length=100, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(default='ACTIF', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'listes_noire',
                'db_table': 'listes_noire',
            },
        ),
        migrations.CreateModel(
            name='TypeListeNoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('niveau_risque', models.CharField(blank=True, default='FAIBLE', max_length=50, null=True)),
                ('statut', models.CharField(default='ACTIF', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'types_liste_noire',
            },
        ),
    ]
