# Generated by Django 6.0.3 on 2026-06-17 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0002_initial'),
        ('liste_noire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlistenoire',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectionlistenoire',
            name='porte_entree',
            field=models.ForeignKey(db_column='id_porte_entree', on_delete=django.db.models.deletion.CASCADE, to='entreprise.porteentree'),
        ),
        migrations.AddField(
            model_name='detectionlistenoire',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listenoire',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listenoire',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectionlistenoire',
            name='liste_noire',
            field=models.ForeignKey(db_column='id_liste_noire', on_delete=django.db.models.deletion.CASCADE, to='liste_noire.listenoire'),
        ),
        migrations.AddField(
            model_name='typelistenoire',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typelistenoire',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listenoire',
            name='type_liste_noire',
            field=models.ForeignKey(db_column='id_type_liste_noire', on_delete=django.db.models.deletion.CASCADE, to='liste_noire.typelistenoire'),
        ),
        migrations.AddIndex(
            model_name='detectionlistenoire',
            index=models.Index(fields=['statut'], name='detections__statut_e1cc2d_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionlistenoire',
            index=models.Index(fields=['porte_entree'], name='detections__id_port_f77f57_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionlistenoire',
            index=models.Index(fields=['liste_noire'], name='detections__id_list_f775fb_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionlistenoire',
            index=models.Index(fields=['date_detection'], name='detections__date_de_3a0c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='typelistenoire',
            index=models.Index(fields=['nom'], name='types_liste_nom_f22534_idx'),
        ),
        migrations.AddIndex(
            model_name='typelistenoire',
            index=models.Index(fields=['statut'], name='types_liste_statut_b480ee_idx'),
        ),
        migrations.AddIndex(
            model_name='listenoire',
            index=models.Index(fields=['nom'], name='listes_noir_nom_4438d1_idx'),
        ),
        migrations.AddIndex(
            model_name='listenoire',
            index=models.Index(fields=['prenom'], name='listes_noir_prenom_73592d_idx'),
        ),
        migrations.AddIndex(
            model_name='listenoire',
            index=models.Index(fields=['statut'], name='listes_noir_statut_07aa07_idx'),
        ),
        migrations.AddIndex(
            model_name='listenoire',
            index=models.Index(fields=['type_liste_noire'], name='listes_noir_id_type_da9bef_idx'),
        ),
    ]
