# Generated by Django 5.2.15 on 2026-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste_noire', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenoire',
            name='blocage_automatique',
            field=models.BooleanField(default=True, help_text="Si coché, l'enregistrement est automatiquement bloqué (BLOCK). Sinon, avertissement seulement (WARN)."),
        ),
    ]
