# Generated by Django 6.0.3 on 2026-06-17 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionObjetOublie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_detection', models.DateTimeField(blank=True, null=True)),
                ('confiance', models.CharField(blank=True, default='MOYENNE', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(default='ACTIF', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'detections_objets_oublies',
                'db_table': 'detections_objets_oublies',
            },
        ),
        migrations.CreateModel(
            name='ObjetOublie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nom_objet', models.CharField(max_length=255)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_trouve', models.DateTimeField(blank=True, null=True)),
                ('lieu_trouve', models.CharField(blank=True, max_length=255, null=True)),
                ('date_remise', models.DateTimeField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('photo_objet', models.TextField(blank=True, null=True)),
                ('personne_recupere', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(default='NON_RESTITUÉ', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'objets_oublies',
                'db_table': 'objets_oublies',
            },
        ),
    ]
