# Generated by Django 6.0.3 on 2026-06-17 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0002_initial'),
        ('objets_oublies', '0001_initial'),
        ('visites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionobjetoublie',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectionobjetoublie',
            name='porte_entree',
            field=models.ForeignKey(db_column='id_porte_entree', on_delete=django.db.models.deletion.CASCADE, to='entreprise.porteentree'),
        ),
        migrations.AddField(
            model_name='detectionobjetoublie',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objetoublie',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objetoublie',
            name='departement',
            field=models.ForeignKey(blank=True, db_column='id_departement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.departement'),
        ),
        migrations.AddField(
            model_name='objetoublie',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objetoublie',
            name='visite',
            field=models.ForeignKey(blank=True, db_column='id_visite', null=True, on_delete=django.db.models.deletion.SET_NULL, to='visites.visite'),
        ),
        migrations.AddField(
            model_name='detectionobjetoublie',
            name='objet_oublie',
            field=models.ForeignKey(db_column='id_objet_oublie', on_delete=django.db.models.deletion.CASCADE, to='objets_oublies.objetoublie'),
        ),
        migrations.AddIndex(
            model_name='objetoublie',
            index=models.Index(fields=['statut'], name='objets_oubl_statut_0068b5_idx'),
        ),
        migrations.AddIndex(
            model_name='objetoublie',
            index=models.Index(fields=['date_trouve'], name='objets_oubl_date_tr_2787cc_idx'),
        ),
        migrations.AddIndex(
            model_name='objetoublie',
            index=models.Index(fields=['categorie'], name='objets_oubl_categor_df6c84_idx'),
        ),
        migrations.AddIndex(
            model_name='objetoublie',
            index=models.Index(fields=['visite'], name='objets_oubl_id_visi_9770c7_idx'),
        ),
        migrations.AddIndex(
            model_name='objetoublie',
            index=models.Index(fields=['departement'], name='objets_oubl_id_depa_1b9a47_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionobjetoublie',
            index=models.Index(fields=['statut'], name='detections__statut_e5e6a7_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionobjetoublie',
            index=models.Index(fields=['porte_entree'], name='detections__id_port_f0cda2_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionobjetoublie',
            index=models.Index(fields=['objet_oublie'], name='detections__id_obje_d19db1_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionobjetoublie',
            index=models.Index(fields=['date_detection'], name='detections__date_de_b715c2_idx'),
        ),
    ]
