# Generated by Django 5.2.15 on 2026-08-08 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0007_add_exception_jour'),
        ('objets_oublies', '0002_initial'),
        ('visites', '0009_add_flag_avertissement_to_visiteur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='objetoublie',
            name='visiteur',
            field=models.ForeignKey(blank=True, db_column='id_visiteur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objets_oublies', to='visites.visiteur'),
        ),
        migrations.AddIndex(
            model_name='objetoublie',
            index=models.Index(fields=['visiteur'], name='objets_oubl_id_visi_95e9ce_idx'),
        ),
    ]
