# Generated by Django 6.0.3 on 2026-06-17 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_detection', models.DateTimeField(blank=True, null=True)),
                ('confiance', models.CharField(blank=True, default='MOYENNE', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(default='ACTIF', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'detections_incident',
                'db_table': 'detections_incident',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_incident', models.CharField(choices=[('INTRUSION', 'Intrusion'), ('VOL', 'Vol'), ('VIOLENCE', 'Violence / Agression'), ('INCENDIE', 'Incendie'), ('ALARME', 'Alarme'), ('ACCIDENT', 'Accident'), ('DOMMAGE', 'Dégât matériel'), ('SUSPICION', 'Comportement suspect'), ('INFRACTION', 'Infraction'), ('AUTRE', 'Autre incident')], max_length=50)),
                ('motif', models.TextField(blank=True, null=True)),
                ('date_incident', models.DateTimeField(blank=True, null=True)),
                ('gravite', models.CharField(default='MOYENNE', max_length=50)),
                ('statut', models.CharField(default='OUVERT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
    ]
