# Generated by Django 6.0.3 on 2026-06-17 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('visites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionincident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectionincident',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='visite',
            field=models.ForeignKey(db_column='id_visite', on_delete=django.db.models.deletion.CASCADE, to='visites.visite'),
        ),
        migrations.AddField(
            model_name='detectionincident',
            name='incident',
            field=models.ForeignKey(db_column='id_incident', on_delete=django.db.models.deletion.CASCADE, to='incidents.incident'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['statut'], name='incidents_statut_da7753_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['date_incident'], name='incidents_date_in_292596_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['visite'], name='incidents_id_visi_07915f_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionincident',
            index=models.Index(fields=['statut'], name='detections__statut_0448cc_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionincident',
            index=models.Index(fields=['incident'], name='detections__id_inci_e8d562_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionincident',
            index=models.Index(fields=['date_detection'], name='detections__date_de_c0c667_idx'),
        ),
    ]
