# Generated by Django 5.2.15 on 2026-07-22 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_initial'),
        ('visites', '0008_add_departement_to_visite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='personne',
            field=models.ForeignKey(blank=True, db_column='id_personne', null=True, on_delete=django.db.models.deletion.SET_NULL, to='visites.visiteur'),
        ),
        migrations.AddField(
            model_name='incident',
            name='titre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='gravite',
            field=models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('GRAVE', 'Grave'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='statut',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('RESOLU', 'Résolu'), ('CLASSE_SANS_SUITE', 'Classé sans suite')], default='OUVERT', max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='visite',
            field=models.ForeignKey(blank=True, db_column='id_visite', null=True, on_delete=django.db.models.deletion.SET_NULL, to='visites.visite'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['personne'], name='incidents_id_pers_5a7330_idx'),
        ),
    ]
