# Generated by Django 5.2.15 on 2026-07-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_convert_type_incident_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='titre',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='DetectionIncident',
        ),
    ]
