# Generated by Django 5.2.15 on 2026-08-10 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_alter_incident_titre_delete_detectionincident'),
        ('visites', '0009_add_flag_avertissement_to_visiteur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visiteur_nom', models.CharField(max_length=255)),
                ('visiteur_prenom', models.CharField(max_length=255)),
                ('visiteur_nip', models.CharField(blank=True, max_length=100, null=True)),
                ('visiteur_piece', models.CharField(blank=True, max_length=100, null=True)),
                ('decision', models.CharField(choices=[('REFUSE_SYSTEME', 'Refusé (système — Liste Noire)'), ('REFUSE_AGENT', 'Refusé (agent)'), ('AUTORISE', 'Autorisé (agent)')], max_length=50)),
                ('type_detection', models.CharField(max_length=50)),
                ('detail_detection', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visite', models.ForeignKey(blank=True, db_column='id_visite', null=True, on_delete=django.db.models.deletion.SET_NULL, to='visites.visite')),
            ],
            options={
                'verbose_name': 'Décision de détection',
                'verbose_name_plural': 'Décisions de détection',
                'db_table': 'detection_decisions',
                'ordering': ['-created_at'],
            },
        ),
    ]
